openapi: 3.0.3
info:
  title: Khách Hàng API
  version: v1
  description: API quản lý khách hàng gồm CRUD operations, tìm kiếm và quản lý thông tin khách hàng
servers:
  - url: https://localhost:7000
paths:
  /api/KhachHang:
    get:
      tags: [Khách Hàng]
      summary: Lấy danh sách tất cả khách hàng
      description: Trả về danh sách tất cả khách hàng trong hệ thống
      responses:
        '200':
          description: Lấy danh sách khách hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseKhachHangList'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
    post:
      tags: [Khách Hàng]
      summary: Tạo khách hàng mới
      description: Tạo một khách hàng mới trong hệ thống
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKhachHangDto'
            example:
              TenKhachHang: "Nguyễn Văn A"
              DiaChi: "123 Đường ABC, Quận 1, TP.HCM"
              DiemTichLuy: 100
              HangThanhVien: "Vàng"
              MaTaiKhoan: 1
      responses:
        '201':
          description: Tạo khách hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseKhachHang'
        '400':
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/KhachHang/{id}:
    get:
      tags: [Khách Hàng]
      summary: Lấy thông tin khách hàng theo ID
      description: Trả về thông tin chi tiết của một khách hàng dựa trên mã khách hàng
      parameters:
        - name: id
          in: path
          required: true
          description: Mã khách hàng
          schema:
            type: integer
            format: int32
          example: 1
      responses:
        '200':
          description: Lấy thông tin khách hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseKhachHang'
        '404':
          description: Không tìm thấy khách hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
    put:
      tags: [Khách Hàng]
      summary: Cập nhật thông tin khách hàng
      description: Cập nhật thông tin của một khách hàng dựa trên mã khách hàng
      parameters:
        - name: id
          in: path
          required: true
          description: Mã khách hàng
          schema:
            type: integer
            format: int32
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateKhachHangDto'
            example:
              MaKhachHang: 1
              TenKhachHang: "Nguyễn Văn A"
              DiaChi: "123 Đường ABC, Quận 1, TP.HCM"
              DiemTichLuy: 150
              HangThanhVien: "Kim Cương"
              MaTaiKhoan: 1
              TrangThai: "Active"
      responses:
        '200':
          description: Cập nhật khách hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseKhachHang'
        '400':
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: Không tìm thấy khách hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
    delete:
      tags: [Khách Hàng]
      summary: Xóa khách hàng
      description: Xóa một khách hàng khỏi hệ thống dựa trên mã khách hàng
      parameters:
        - name: id
          in: path
          required: true
          description: Mã khách hàng
          schema:
            type: integer
            format: int32
          example: 1
      responses:
        '200':
          description: Xóa khách hàng thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: Không tìm thấy khách hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /api/KhachHang/search:
    get:
      tags: [Khách Hàng]
      summary: Tìm kiếm khách hàng
      description: Tìm kiếm khách hàng dựa trên từ khóa (tên, địa chỉ, hạng thành viên)
      parameters:
        - name: searchTerm
          in: query
          required: true
          description: Từ khóa tìm kiếm
          schema:
            type: string
          example: "Nguyễn Văn A"
      responses:
        '200':
          description: Tìm kiếm thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseKhachHangList'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
components:
  schemas:
    ApiResponseObject:
      type: object
      properties:
        success:
          type: boolean
          description: Trạng thái thành công
          example: true
        message:
          type: string
          description: Thông báo
          example: "Thành công"
        data:
          nullable: true
          description: Dữ liệu trả về
    ApiResponseKhachHang:
      type: object
      properties:
        success:
          type: boolean
          description: Trạng thái thành công
          example: true
        message:
          type: string
          description: Thông báo
          example: "Lấy thông tin khách hàng thành công"
        data:
          $ref: '#/components/schemas/KhachHangDto'
    ApiResponseKhachHangList:
      type: object
      properties:
        success:
          type: boolean
          description: Trạng thái thành công
          example: true
        message:
          type: string
          description: Thông báo
          example: "Lấy danh sách khách hàng thành công"
        data:
          type: array
          items:
            $ref: '#/components/schemas/KhachHangDto'
    KhachHangDto:
      type: object
      properties:
        MaKhachHang:
          type: integer
          format: int32
          description: Mã khách hàng
          example: 1
        TenKhachHang:
          type: string
          description: Tên khách hàng
          example: "Nguyễn Văn A"
        DiaChi:
          type: string
          nullable: true
          description: Địa chỉ
          example: "123 Đường ABC, Quận 1, TP.HCM"
        DiemTichLuy:
          type: integer
          format: int32
          nullable: true
          description: Điểm tích lũy
          example: 100
        HangThanhVien:
          type: string
          nullable: true
          description: Hạng thành viên
          example: "Vàng"
        MaTaiKhoan:
          type: integer
          format: int32
          nullable: true
          description: Mã tài khoản
          example: 1
        TrangThai:
          type: string
          nullable: true
          description: Trạng thái
          example: "Active"
    CreateKhachHangDto:
      type: object
      required: [TenKhachHang]
      properties:
        TenKhachHang:
          type: string
          maxLength: 200
          description: Tên khách hàng (bắt buộc, tối đa 200 ký tự)
          example: "Nguyễn Văn A"
        DiaChi:
          type: string
          nullable: true
          description: Địa chỉ (không bắt buộc)
          example: "123 Đường ABC, Quận 1, TP.HCM"
        DiemTichLuy:
          type: integer
          format: int32
          minimum: 0
          nullable: true
          description: Điểm tích lũy (không bắt buộc, tối thiểu 0)
          example: 100
        HangThanhVien:
          type: string
          nullable: true
          description: Hạng thành viên (không bắt buộc)
          example: "Vàng"
        MaTaiKhoan:
          type: integer
          format: int32
          nullable: true
          description: Mã tài khoản (không bắt buộc)
          example: 1
    UpdateKhachHangDto:
      type: object
      required: [MaKhachHang, TenKhachHang]
      properties:
        MaKhachHang:
          type: integer
          format: int32
          description: Mã khách hàng (bắt buộc)
          example: 1
        TenKhachHang:
          type: string
          maxLength: 200
          description: Tên khách hàng (bắt buộc, tối đa 200 ký tự)
          example: "Nguyễn Văn A"
        DiaChi:
          type: string
          nullable: true
          description: Địa chỉ (không bắt buộc)
          example: "123 Đường ABC, Quận 1, TP.HCM"
        DiemTichLuy:
          type: integer
          format: int32
          minimum: 0
          nullable: true
          description: Điểm tích lũy (không bắt buộc, tối thiểu 0)
          example: 150
        HangThanhVien:
          type: string
          nullable: true
          description: Hạng thành viên (không bắt buộc)
          example: "Kim Cương"
        MaTaiKhoan:
          type: integer
          format: int32
          nullable: true
          description: Mã tài khoản (không bắt buộc)
          example: 1
        TrangThai:
          type: string
          nullable: true
          description: Trạng thái (không bắt buộc)
          example: "Active"